-- View Structure

-- MySQL dump 10.13
--
-- Host: 20.235.14.88    Database: d003_srtprd
-- ------------------------------------------------------

DROP VIEW IF EXISTS `vw_mcc_milk_collection`;
CREATE ALGORITHM=UNDEFINED DEFINER=`appuser`@`%` SQL SECURITY DEFINER VIEW `vw_mcc_milk_collection` AS select `m005`.`MCC_Code` AS `MCC_Code`,`m005`.`MCC_Name` AS `MCC_Name`,`ml02`.`State_Name` AS `State_Name`,`ml03`.`District_Name` AS `District_Name`,`ml04`.`Taluka_Name` AS `Taluka_Name`,`ml05`.`Village_Name` AS `Village_Name`,`ml05`.`Pin_Code` AS `Pin_Code`,`c015`.`CollectionShift_Name` AS `CollectionShift_Name`,`c011`.`MilkType_Name` AS `MilkType_Name`,`c014`.`MCCType_Name` AS `MCCType_Name`,`c023`.`MCCWorkType_Name` AS `MCCWorkType_Name`,cast(`f010`.`Collection_Date` as date) AS `Collection_Date`,`f010`.`Agent_Quantity_Kg` AS `Agent_Quantity_Kg`,`f010`.`Agent_Quantity_Ltr` AS `Agent_Quantity_Ltr`,`f010`.`Agent_Fat` AS `Agent_Fat`,`f010`.`Agent_SNF` AS `Agent_SNF`,`f010`.`Agent_Fat_Kg` AS `Agent_Fat_Kg`,`f010`.`Agent_SNF_Kg` AS `Agent_SNF_Kg`,`f010`.`Dairy_Quantity_Kg` AS `Dairy_Quantity_Kg`,`f010`.`Dairy_Quantity_Ltr` AS `Dairy_Quantity_Ltr`,`f010`.`Dairy_Fat` AS `Dairy_Fat`,`f010`.`Dairy_SNF` AS `Dairy_SNF`,`f010`.`Dairy_Protein` AS `Dairy_Protein`,`f010`.`Dairy_Ash` AS `Dairy_Ash`,`f010`.`Dairy_Sodium` AS `Dairy_Sodium`,`f010`.`Dairy_Fat_Kg` AS `Dairy_Fat_Kg`,`f010`.`Dairy_SNF_Kg` AS `Dairy_SNF_Kg`,`f010`.`FatKG_GainLoss` AS `FatKG_GainLoss`,`f010`.`SNFKG_GainLoss` AS `SNFKG_GainLoss`,`f010`.`FatKG_Rate` AS `FatKG_Rate`,`f010`.`SNFKG_Rate` AS `SNFKG_Rate`,`f010`.`Total_GainLoss` AS `Total_GainLoss`,`f010`.`AgentCost` AS `AgentCost`,`f010`.`TransporterCost` AS `TransporterCost`,`f010`.`MilkPrice` AS `MilkPrice`,`f010`.`MilkRate` AS `MilkRate`,`f010`.`Dairy_Sour_Ltr` AS `Dairy_Sour_Ltr` from (((((((((`f010_milkcollectionmcc_final` `f010` join `m005_mcc` `m005` on(((`m005`.`Org_Id` = `f010`.`Org_Id`) and (`m005`.`MCC_Id` = `f010`.`MCC_Id`)))) join `ml02_state` `ml02` on(((`m005`.`Org_Id` = `ml02`.`Org_Id`) and (`m005`.`State_Id` = `ml02`.`State_Id`)))) join `ml03_district` `ml03` on(((`m005`.`Org_Id` = `ml03`.`Org_Id`) and (`m005`.`District_Id` = `ml03`.`District_Id`)))) join `ml04_taluka` `ml04` on(((`m005`.`Org_Id` = `ml04`.`Org_Id`) and (`m005`.`Taluka_Id` = `ml04`.`Taluka_Id`)))) join `ml05_village` `ml05` on(((`m005`.`Org_Id` = `ml05`.`Org_Id`) and (`m005`.`Village_Id` = `ml05`.`Village_Id`)))) join `c015_collectionshift` `c015` on((ifnull(`f010`.`CollectionShift_Id`,'C015003') = `c015`.`CollectionShift_Id`))) join `c011_milktype` `c011` on((`c011`.`MilkType_Id` = `f010`.`MilkType_Id`))) join `c014_mcctype` `c014` on((`c014`.`MCCType_Id` = `m005`.`MCCType_Id`))) join `c023_mccworktype` `c023` on((`c023`.`MCCWorkType_Id` = `m005`.`MCCWorkType_Id`))) where (`f010`.`Org_Id` = 'C005');

-- Dump completed on 2026-05-12 17:16:23
