<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\AdminConsole_API\DAL\CommonAPIDAL.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.143" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="itext.pdfhtml" Version="5.0.1" />
    <PackageReference Include="itext7" Version="8.0.1" />
    <PackageReference Include="itext7.bouncy-castle-fips-adapter" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="MySql.Data" Version="8.0.33" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\AgentApp_API\Views\" />
    <Folder Include="Areas\ChemistApp_API\Models\" />
    <Folder Include="Areas\ChemistApp_API\Views\" />
    <Folder Include="Areas\DriverApp_API\Models\" />
    <Folder Include="Areas\DriverApp_API\Views\" />
    <Folder Include="Areas\FarmerApp_API\Views\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
